version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "snapsnapturtle"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "snapsnapturtle"
